import { reactive } from "vue";

export const store =reactive ({
    searchText: '',
    searchedByText: [],
    settedCategory: 'general',
    settedCountry: 'it',
    categories:[
        "business",
        "entertainment",
        "general",
        "health",
        "science",
        "sports",
        "technology"
    ],
    nations: {
        ar: "Argentina,",
        at:"Austria,",
        au: "Australia,",
        be: "Belgium,",
        bg: "Bulgaria,",
        br: "Brazil,",
        ca: "Canada,",
        ch: "Cina,",
        cn: "Cina,",
        co: "Colombia,",
        cu: "Cuba,",
        cz: "Repubblica Ceca,",
        de: "Germania,",
        gr: "Grecia,",
        hk: "Hong Kong,",
        hu: "Ungheria,",
        in: "India,",
        id: "Indonesia,",
        ie: "Irlanda,",
        il: "Israele,",
        it: "Italia,",
        jp: "Giappone,",
        lv: "Lettonia,",
        lt: "Lituania,",
        my: "Malesia,",
        mx: "Messico,",
        ma: "Marocco,",
        nl: "Olanda,",
        nz: "Nuova Zelanda,",
        ng: "Nigeria,",
        no: "Norvegia,",
        ph: "Filippine,",
        pl: "Polonia,",
        pt: "Portogallo,",
        ro: "Romania,",
        ru: "Russia,",
        sa: "Arabia Saudita,",
        rs: "Serbia,",
        sg: "Singapore,",
        sk: "Slovacchia,",
        si: "Slovenia,",
        za: "Sud Africa,",
        kr: "Corea del Sud,",
        se: "Svezia,",
        ch: "Svizzera,",
        tw: "Taiwan,",
        th: "Tailandia,",
        tr: "Turkia,",
        ae: "Emirati Arabi Uniti,",
        ua: "Ucraina,",
        gb: "Gran Bretagna,",
        us: "Stati Uniti,",
        ve: "Venezuela",
    }
});